DROP DATABASE IF EXISTS GRTH;
CREATE DATABASE GRTH;

/* JOINTURE */
DROP TABLE IF EXISTS "Twinning";
DROP TABLE IF EXISTS "Family";

DROP TABLE IF EXISTS "Image";
DROP TABLE IF EXISTS "Qualification";
DROP TABLE IF EXISTS "Housing";
DROP TABLE IF EXISTS "Owner";
DROP TABLE IF EXISTS "Applicant";
DROP TABLE IF EXISTS "User";
DROP TABLE IF EXISTS "Member";

DROP TYPE IF EXISTS MEMBER_TYPE;
DROP TYPE IF EXISTS HOUSING_TYPE;
DROP TYPE IF EXISTS NOTE;

CREATE TYPE MEMBER_TYPE AS ENUM ('Child', 'Partner', 'User');
CREATE TYPE HOUSING_TYPE AS ENUM ('1', '2', '2.5', '3', '3.5', '4', '4.5', '5', '5.5', '6');
CREATE TYPE NOTE AS ENUM ('1', '2', '3', '4', '5');

CREATE TABLE "Member" (
"Id" SERIAL PRIMARY KEY,
"FirstName" CHAR(50) NOT NULL,
"LastName" CHAR(50) NOT NULL,
"Email" CHAR(50) NULL,
"Type" MEMBER_TYPE NOT NULL,
"PhoneNumber" CHAR(20) NULL,
"BirthDate" DATE NOT NULL
);

CREATE TABLE "User" (
"Id" INTEGER PRIMARY KEY,
"FolderNumber" INTEGER NOT NULL,
"Address" CHAR(100) NOT NULL,
"City" CHAR(50) NOT NULL,
"PostalCode" CHAR(6),
"Password" CHAR(50),
FOREIGN KEY ("Id") REFERENCES "Member" ("Id") ON UPDATE CASCADE ON DELETE CASCADE 
);

CREATE TABLE "Applicant" (
"Id" INTEGER PRIMARY KEY,
"HousingTypeSought" HOUSING_TYPE NOT NULL,
"FamilyIncome" DOUBLE PRECISION,
"HaveAnimals" BOOLEAN,
"HaveLease" BOOLEAN,
FOREIGN KEY ("Id") REFERENCES "User" ("Id") ON UPDATE CASCADE ON DELETE CASCADE 
);

CREATE TABLE "Owner" (
"Id" INTEGER PRIMARY KEY,
FOREIGN KEY ("Id") REFERENCES "User" ("Id") ON UPDATE CASCADE ON DELETE CASCADE 
);

CREATE TABLE "Family" (
"MemberId" INTEGER NOT NULL,
"ApplicantId" INTEGER NOT NULL,
FOREIGN KEY ("MemberId") REFERENCES "Member" ("Id") ON UPDATE CASCADE ON DELETE CASCADE,
FOREIGN KEY ("ApplicantId") REFERENCES "Applicant" ("Id") ON UPDATE CASCADE ON DELETE CASCADE 
);

CREATE TABLE "Housing" (
"Id" SERIAL PRIMARY KEY,
"OwnerId" INTEGER NOT NULL,
"ContactId" INTEGER NOT NULL,
"Address" CHAR(100) NOT NULL,
"Sector" CHAR(50) NOT NULL,
"SchoolArea" CHAR(50),
"RoomCount" DOUBLE PRECISION NOT NULL,
"ParkingCount" SMALLINT DEFAULT 0,
"Level" CHAR(10),
"AllowAnimals" BOOLEAN DEFAULT TRUE,
"Heated" BOOLEAN DEFAULT FALSE,
"Enlightened" BOOLEAN DEFAULT FALSE,
"SemiFurnished" BOOLEAN DEFAULT FALSE,
"FirstRentFree" BOOLEAN DEFAULT FALSE,
"RentCost" DOUBLE PRECISION NOT NULL,
"EnergyCost" DOUBLE PRECISION NOT NULL,
"Note" CHAR(254),
"ElectronicSignature" CHAR(50),
FOREIGN KEY ("OwnerId") REFERENCES "Owner" ("Id"),
FOREIGN KEY ("ContactId") REFERENCES "Member" ("Id")
);

CREATE TABLE "Twinning" (
"IdApplicant" INTEGER,
"IdHousing" INTEGER,
PRIMARY KEY ("IdApplicant", "IdHousing"),
FOREIGN KEY ("IdHousing") REFERENCES "Housing"("Id") ON UPDATE CASCADE ON DELETE CASCADE ,
FOREIGN KEY ("IdApplicant") REFERENCES "Applicant"("Id") ON UPDATE CASCADE ON DELETE CASCADE 
);

CREATE TABLE "Qualification" (
"Id" SERIAL PRIMARY KEY,
"HousingId" INTEGER NOT NULL,
"HaveMoldTraces" BOOLEAN NOT NULL DEFAULT FALSE,
"StairSafety" NOTE NOT NULL,
"PeronSafety" NOTE NOT NULL,
"LightningSafety" NOTE NOT NULL,
"DetectorSafety" NOTE NOT NULL,
"Cleanliness" NOTE NOT NULL,
"WindowsQuality" NOTE NOT NULL,
"DoorsQuality" NOTE NOT NULL,
"FittingsQuality" NOTE NOT NULL,
"ToiletQuality" NOTE NOT NULL,
"BathShowerQuality" NOTE NOT NULL,
"GeneralMaintenance" NOTE NOT NULL,
"PestProblem" BOOLEAN NOT NULL DEFAULT FALSE,
"FinalScore" SMALLINT,
FOREIGN KEY ("HousingId") REFERENCES "Housing" ("Id") ON UPDATE CASCADE ON DELETE CASCADE 
);

CREATE TABLE "Image" (
"Id" SERIAL PRIMARY KEY,
"QualificationId" INTEGER NOT NULL,
"Note" CHAR(50) NULL,
"Path" CHAR(254) NOT NULL,
FOREIGN KEY ("QualificationId") REFERENCES "Qualification" ("Id") ON UPDATE CASCADE ON DELETE CASCADE 
); 