DROP DATABASE IF EXISTS GRTH;
CREATE DATABASE GRTH;

/* JOINTURE */
DROP TABLE IF EXISTS "Twinning";
DROP TABLE IF EXISTS "Family";

DROP TABLE IF EXISTS "Image";
DROP TABLE IF EXISTS "Qualification";
DROP TABLE IF EXISTS "Housing";
DROP TABLE IF EXISTS "Owner";
DROP TABLE IF EXISTS "Applicant";
DROP TABLE IF EXISTS "User";
DROP TABLE IF EXISTS "Member";

DROP TYPE IF EXISTS MEMBER_TYPE;
DROP TYPE IF EXISTS HOUSING_TYPE;
DROP TYPE IF EXISTS NOTE;
